### searh store by name
GET http://localhost:8080/api/store/search?keyword=광화문&page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIzMTg5OTA2LCJleHAiOjE3MjMyNzYzMDZ9.lOZG-JPhAq9NQc2DML40Ctul5l8uACJ1SzQPJBE7cIGmKAVvjUqicq3r1P7Ixl96GBRNubkQ8ZGu0J5m__1o0A

### searh store by alphabetical order
GET http://localhost:8080/api/store/search/alphabet?page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIzMTg5OTA2LCJleHAiOjE3MjMyNzYzMDZ9.lOZG-JPhAq9NQc2DML40Ctul5l8uACJ1SzQPJBE7cIGmKAVvjUqicq3r1P7Ixl96GBRNubkQ8ZGu0J5m__1o0A

### searh store by rating order
GET http://localhost:8080/api/store/search/rating?page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIzMTg5OTA2LCJleHAiOjE3MjMyNzYzMDZ9.lOZG-JPhAq9NQc2DML40Ctul5l8uACJ1SzQPJBE7cIGmKAVvjUqicq3r1P7Ixl96GBRNubkQ8ZGu0J5m__1o0A

### searh store by distance order
GET http://localhost:8080/api/store/search/distance?address=대구광역시 북구 대학로 85&page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIzMTg5OTA2LCJleHAiOjE3MjMyNzYzMDZ9.lOZG-JPhAq9NQc2DML40Ctul5l8uACJ1SzQPJBE7cIGmKAVvjUqicq3r1P7Ixl96GBRNubkQ8ZGu0J5m__1o0A

### searh store
GET http://localhost:8080/api/store/search/detail?id=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIzMTg5OTA2LCJleHAiOjE3MjMyNzYzMDZ9.lOZG-JPhAq9NQc2DML40Ctul5l8uACJ1SzQPJBE7cIGmKAVvjUqicq3r1P7Ixl96GBRNubkQ8ZGu0J5m__1o0A

