### searh reservation by customer
GET http://localhost:8080/api/reservation/customer/search?page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzEwMDU5NiwiZXhwIjoxNzIzMTg2OTk2fQ.5OpdnuNb8C3oiXVGmLX7Fb0nbEhNqSeMHpQkPnJFdaRqcJ1EPR9-WENDREO5MI1i_ANf3wsXsfG168xg7J8SBA

### searh reservation by customer and store
GET http://localhost:8080/api/reservation/customer/search/2?page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMzEwMDU5NiwiZXhwIjoxNzIzMTg2OTk2fQ.5OpdnuNb8C3oiXVGmLX7Fb0nbEhNqSeMHpQkPnJFdaRqcJ1EPR9-WENDREO5MI1i_ANf3wsXsfG168xg7J8SBA

### searh reservation by partner
GET http://localhost:8080/api/reservation/partner/search/1?date=2024-07-30&page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIzMDk3MTA3LCJleHAiOjE3MjMxODM1MDd9.aFhGdAwzcnzp4FDIzzvvpmbrs8CY4FB0_CBFikEPqMkEiAlblgYVIpoQH_f4_StvvcNvepDOl82usQs_qKyPNA
