server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjuuujh/store-msa-config # 설정파일 있는 git 주소
          default-label: master # 설정파일 있는 git branch
        encrypt:
          enabled: true
#          ignoreLocalSshSettings: true
#          hostKey: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
#          # hostKey를 base64 인코딩한 값
#          hostKeyAlgorithm: ecdsa-sha2-nistp256 # 비대칭키 생성 알고리즘
#          privateKey: |
#            -----BEGIN EC PRIVATE KEY-----
#            -----END EC PRIVATE KEY-----

encrypt:
  key-store:
    alias: encryptionKey
    password: storeEncryptionKey
    location: file:/encryptionKey.jks

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
